### ISSUE TITLE
Re-keying Keys

### ISSUE THREAD

**Issue by Pigyface25** [Darmo117/LockableDoors#1]
It wont let me re-key my key, I put it into the Locksmithing Station, enter in a new name but it wont let me take it out
![image](https://user-images.githubusercontent.com/45637772/216840350-91b30f67-818b-414d-b20a-4816c71062d8.png)

**Comment by DamiaV** [comment]
Hi, that is intended. You can rename locks but not keys. If you do not need a key anymore, you can smelt it in a furnace to get back an iron nugget.
